# atj theme

"attribute" = "blue"
"type" = "shade06"
"type.enum.variant" = "purple"
"constructor" = "shade06"

"constant" = "darker_blue"
"constant.builtin.boolean" = "blue"
"constant.character" = "blue"
"constant.characted.escape" = "blue"
"constant.numeric" = "blue"

"string" = "green"
"string.regexp" = "blue"
"string.special" = { fg = "dark_red", modifiers = ["underlined"] }

"comment" = "gray"

"variable" = "purple"
"variable.builtin" = { fg = "purple", modifiers = ["underlined"] }
"variable.parameter" = "purple"
"variable.other.member" = "purple"

"label" = { fg = "darker_blue", modifiers = ["underlined"] }
"punctuation" = "shade06"

"keyword" = "darker_blue"
"keyword.control.exception" = "darker_blue"

"operator" = "light_purple"

"function" = "shade06"
"function.macro" = "yellow"
"function.builtin" = { fg = "shade06", modifiers = ["italic"] }
"function.special" = "dark_red"
"function.method" = "dark_yellow"

"tag" = "darker_blue"
"special" = "shade06"
"namespace" = "darker_blue"

"markup.bold" = { fg = "shade06", modifiers = ["bold"] }
"markup.italic" = { fg = "shade06", modifiers = ["italic"] }
"markup.strikethrough" = { fg = "shade06", modifiers = ["crossed_out"] }
"markup.heading" = { fg = "purple", modifiers = ["bold"] }
"markup.list" = "darker_blue"
"markup.list.numbered" = "darker_blue"
"markup.list.unnumbered" = "darker_blue"
"markup.link.url" = "shade06"
"markup.link.text" = { fg = "dark_blue", modifiers = ['underlined'] }
"markup.link.label" = "dark_blue"
"markup.quote" = "green"
"markup.raw" = "green"
"markup.raw.inline" = "green"
"markup.raw.block" = "green"

"diff.plus" = "diff_green"
"diff.minus" = "diff_red"
"diff.delta" = "diff_blue"

# ui specific
"ui.background" = { bg = "shade00" }                                            # .separator
"ui.cursor" = { bg = "light_blue" }
# "ui.cursor.insert" = { bg = "light_yellow", fg = "background" }
"ui.cursor.match" = { bg = "shade03" }
"ui.highlight" = { bg = "faint_blue" }
"ui.cursorline" = { bg = "faint_blue" }
"ui.linenr" = { fg = "shade03" }
"ui.linenr.selected" = { fg = "shade04", bg = "faint_blue", modifiers = ["bold"] }
"ui.statusline" = { fg = "shade04", bg = "shade01" }
"ui.statusline.inactive" = { fg = "shade04", bg = "shade02" }
# "ui.statusline.normal" = { fg = "light_yellow", bg = "darker" }
# "ui.statusline.insert" = { fg = "darker", bg = "purple" }
# "ui.statusline.select" = { fg = "selectionFG", bg = "selection" }
"ui.popup" = { bg = "shade01" }
"ui.window" = { bg = "shade01" }
"ui.help" = { fg = "shade06", bg = "shade01" }
"ui.text" = "shade05"
"ui.text.focus" = "shade04"
"ui.virtual" = "shade03"
"ui.virtual.ruler" = { bg = "shade04" }
"ui.menu" = { fg = "shade05", bg = "shade01" }
"ui.menu.selected" = { fg = "shade01", bg = "shade04" }
"ui.selection" = { bg = "lighter_blue" }
"ui.selection.primary" = { bg = "lighter_blue" }
"hint" = "gray"
"info" = "light_blue"
"warning" = "orange"
"error" = "red"
"diagnostic" = { modifiers = [] }
"diagnostic.hint" = { underline = { color = "gray", style = "line" } }
"diagnostic.info" = { underline = { color = "light_blue", style = "line" } }
"diagnostic.warning" = { underline = { color = "orange", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

[palette]
# E4EAED
shade00 = "#f2f3f7" 
shade01 = "#dadde8" 
shade02 = "#c1c6d9" 
shade03 = "#a9b0ca" 
shade04 = "#525c85" 
shade05 = "#434b6c" 
shade06 = "#343a54" 
shade07 = "#25293c" 

background = "#f2f3f7"
foreground = "#25293c"

light_gray = "#dadde8"
gray = "#525c85"
black = "#25293c"

diff_blue = "#C3D6E8"
faint_blue = "#E8Eef1"
lighter_blue = "#d0eaff"
light_blue = "#99ccff"
blue = "#0073E6"
dark_blue = "#185b93"
darker_blue = "#000080"

purple = "#660E7A"

diff_green = "#C9DEC1"
green = "#00733B"
green_blue = "#458383"


yellow = "#808000"
dark_yellow = "#7A7A43"

orange = "#F49810"

diff_red = "#EBBCBC"
red = "#d90016"
dark_red = "#7F0000"