
# Author: ATJ 

"ui.background" = { bg = "background" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.virtual.whitespace" = "base03"
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.help" = { fg = "base06", bg = "base01" }
"ui.gutter" = { bg = "base01" }

"ui.cursor" = { bg = "light_blue" }
"ui.cursor.primary" = { bg = "light_blue" }
"ui.cursor.match" = { bg = "base03" }
"ui.cursorline.primary" = { bg = "faint_blue" }
"ui.selection" = { bg = "lighter_blue" }


"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "red"

"diagnostic" = { modifiers = ["underlined"] }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base01" }
"ui.bufferline.active" = { fg = "base07", bg = "base00" }

"comment" = { fg = "gray", modifiers = ["italic"] }

"operator" = "black"
"variable" = "purple"
"variable.other.member" = "purple"
"constant.numeric" = "blue"
"constant" = "darker_blue"
"attribute" = "base09"
"type" = "darker_blue"
"string"  = "green"
"constant.character.escape" = "base0C"
"function" = "black"
"constructor" = "black"
"special" = "base0D"
"keyword" = "darker_blue"
"label" = "purple"
"namespace" = "darker_blue"

"markup.heading" = "purple"
"markup.list" = "darker_blue"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { }
"markup.link.text" = { fg = "dark_blue", modifiers = ["underlined"] }
"markup.link.label" = { fg = "darker_blue" }
"markup.quote" = "green"
"markup.raw" = "green"


[palette]
# E4EAED
base00 = "#f2f3f7" 

base01 = "#dadde8" 
base02 = "#c1c6d9" 
base03 = "#a9b0ca" 
base04 = "#525c85" 
base05 = "#434b6c" 
base06 = "#343a54" 

base07 = "#25293c" 

base08 = "#d90016" # +Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#dc9656" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#f7ca88" # Classes, Markup Bold, Search Text Background
base0B = "#00733B" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#86c1b9" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#7cafc2" # Functions, Methods, Attribute IDs, Headings
base0E = "#660E7A" # +Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a16946" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>

background = "#f2f3f7"
foreground = "#25293c"

light_gray = "#dadde8"
gray = "#525c85"
black = "#25293c"

faint_blue = "#E8Eef1"
lighter_blue = "#d0eaff"
light_blue = "#99ccff"
blue = "#0073E6"
dark_blue = "#185b93"
darker_blue = "#000080"

purple = "#660E7A"

green = "#00733B"
red = "#d90016"
