
# Author: ATJ 

"ui.background" = { bg = "background" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.virtual.whitespace" = "base03"
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.help" = { fg = "base06", bg = "base01" }

"ui.cursor" = { bg = "gray", fg = "white" }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "light_blue" }

"ui.cursorline.primary" = { bg = "light_gray"}
"comment" = { fg = "gray", modifiers = ["italic"] }

"operator" = "black"
"variable" = "purple"
"variable.other.member" = "purple"
"constant.numeric" = "blue"
"constant" = "dark_blue"
"attribute" = "base09"
"type" = "dark_blue"
"string"  = "green"
"constant.character.escape" = "base0C"
"function" = "black"
"constructor" = "black"
"special" = "base0D"
"keyword" = "dark_blue"
"label" = "base0E"
"namespace" = "base0E"

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base01" }
"ui.bufferline.active" = { fg = "base07", bg = "base00" }

[palette]
base00 = "#f2f3f7" # Default Background
base01 = "#dadde8" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#c1c6d9" # Selection Background
base03 = "#a9b0ca" # Comments, Invisibles, Line Highlighting
base04 = "#525c85" # Dark Foreground (Used for status bars)
base05 = "#434b6c" # Default Foreground, Caret, Delimiters, Operators
base06 = "#343a54" # Light Foreground (Not often used)
base07 = "#25293c" # Light Background (Not often used)
base08 = "#d90019" # +Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#dc9656" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#f7ca88" # Classes, Markup Bold, Search Text Background
base0B = "#a1b56c" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#86c1b9" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#7cafc2" # Functions, Methods, Attribute IDs, Headings
base0E = "#660E7A" # +Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a16946" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>

background = "#F2F3F7"
foreground = "#262626"

light_gray = "#dadde8"
gray = "#525c85"
black = "#25293c"

light_blue = "#99ccff"
blue = "#0073E6"
dark_blue = "#000080"

purple = "#660E7A"

green = "#00733B"
red = "#d90016"
