# Author: Paul Graydon <p.y.graydon@gmail.com>

inherits = "tokyonight"


"ui.cursor" = { bg = "black" }
"ui.cursor.match" = { fg = "orange", modifiers = ["bold"] }
"ui.cursor.primary" = { bg = "blue", fg = "black"  }
"ui.cursor.primary.select" = { bg = "magenta", fg = "black" }
"ui.cursor.primary.insert" = { bg = "green", fg = "black" }


"ui.statusline.normal" = { fg = "black", bg = "blue" }
"ui.statusline.insert" = { fg = "black", bg = "green" }
"ui.statusline.select" = { fg = "black", bg = "magenta" }

[palette]
background = "#24283b"
background_highlight = "#373d5a"
background_menu = "#1f2335"

