
theme = "cyan_light"

[editor]
line-number = "relative"
cursorline = true
auto-save = true
auto-format = true
color-modes = true
true-color = true
undercurl = true
indent-guides.render = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false


[editor.soft-wrap]
enable = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert.j]
k = "normal_mode"
j = "normal_mode"

[keys.normal.space]
w = ":w"
q = ":q"
c = ":config-reload"
t = ":tree-sitter-highlight-name"

[keys.normal]
i = ["collapse_selection", "insert_mode"]
a = ["move_char_right", "collapse_selection", "insert_mode"]
"}" = ["goto_next_paragraph"]
"{" = ["goto_prev_paragraph"]
"C-c" = ["toggle_comments", "move_line_down"]

# Helix as an IDE
# "A-9" = ":sh sh lazygit-down.sh"
# "A-1" = ":sh sh file-tree-left.sh"
