theme = "atj"

[editor]
line-number = "relative"
cursorline = true
auto-save = true
auto-format = true
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false


[editor.soft-wrap]
# enable = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert.j]
k = "normal_mode"

[keys.normal]
space = { w = ":w", q = ":q", t = ":tree-sitter-scopes", c = ":config-reload" }
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode"]

